// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDn38Cqzh5zR-EXun47CofU-4IWEsYUA',
    appId: '1:455918915116:web:fbe75e7a867e0b39970b89',
    messagingSenderId: '455918915116',
    projectId: 'travel-organizer-proj',
    authDomain: 'travel-organizer-proj.firebaseapp.com',
    storageBucket: 'travel-organizer-proj.firebasestorage.app',
    measurementId: 'G-SEF2JHDMLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNrxmRGlg9D7SIsoVcebJDTD_CNaUb_s',
    appId: '1:455918915116:android:345dc3e936ec71dc970b89',
    messagingSenderId: '455918915116',
    projectId: 'travel-organizer-proj',
    storageBucket: 'travel-organizer-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJY9kQS4bbRFPfKCXzgJ7spYr_rRpVqEE',
    appId: '1:455918915116:ios:cdc9fb9ac68414b0970b89',
    messagingSenderId: '455918915116',
    projectId: 'travel-organizer-proj',
    storageBucket: 'travel-organizer-proj.firebasestorage.app',
    androidClientId: '455918915116-4pbe62gqg567nnju24cvpruindvqmqu3.apps.googleusercontent.com',
    iosClientId: '455918915116-39p95ctf0kju525e20gf8pni55ope1ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJY9kQS4bbRFPfKCXzgJ7spYr_rRpVqEE',
    appId: '1:455918915116:ios:cdc9fb9ac68414b0970b89',
    messagingSenderId: '455918915116',
    projectId: 'travel-organizer-proj',
    storageBucket: 'travel-organizer-proj.firebasestorage.app',
    androidClientId: '455918915116-4pbe62gqg567nnju24cvpruindvqmqu3.apps.googleusercontent.com',
    iosClientId: '455918915116-39p95ctf0kju525e20gf8pni55ope1ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnDn38Cqzh5zR-EXun47CofU-4IWEsYUA',
    appId: '1:455918915116:web:1095a6640a67e066970b89',
    messagingSenderId: '455918915116',
    projectId: 'travel-organizer-proj',
    authDomain: 'travel-organizer-proj.firebaseapp.com',
    storageBucket: 'travel-organizer-proj.firebasestorage.app',
    measurementId: 'G-PBX4K7KQ2F',
  );

}